import type { Metadata } from "next";
import localFont from "next/font/local";
// import { Yellowtail } from "next/font/google";
import { Dancing_Script } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import WhatsappBtn from "@/components/WhatsappBtn";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/sonner";

const pacifico = Dancing_Script({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-primary",
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it">
      <body
        className={`${pacifico.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Toaster richColors />
        <WhatsappBtn />
        <Footer />
      </body>
    </html>
  );
}
